name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: dietpi:rpi_armv8_bullseye
          commands: |
            apt-get -y install git nano wget curl bc jq make cmake ninja python3 python3-pip golang
            pip install request
            git clone https://github.com/lzhiyong/android-sdk-tools && cd android-sdk-tools
            python get_source.py --tags platform-tools-35.0.2
