name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: mboh
        run: |
          sudo apt-get -y install git nano wget curl bc jq make cmake ninja python3 python3-pip golang
          pip3 install request
          git clone https://github.com/lzhiyong/android-sdk-tools && cd android-sdk-tools
          python3 get_source.py --tags platform-tools-35.0.2
