name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          apt-get -y install git nano wget curl bc jq make cmake ninja python3 python-pip
